### ISSUE TITLE
Wireless Module fails when the SSID is an emoji

### ISSUE THREAD

**Issue by lyneca** [jaagr/polybar#1367]
I have my phone's hotspot SSID set to "😶". This displays fine in my terminal and other wifi indicators.
On Polybar's `wireless-network` module, when connected to this network, it shows the `label-disconnected` label, despite the internet being connected. This does not happen when I change the SSID of my phone's hotspot to something other than "😶".

Yes, I realise how niche of an issue this is. Is this a Polybar problem or something else? I believe that I updated Polybar quite recently, and that may have been the cause of this problem.

**Comment by NBonaparte** [comment]
We recently switched to `iw` from `libnl`, so it seems like `iw` might be the issue (if you have it installed).

**Comment by lyneca** [comment]
Could be. I'll have a look in a bit.

**Comment by lyneca** [comment]
Here's what `iwgetid` returns: 
```bash
$ iwgetid
wlp2s0    ESSID:"\xF0\x9F\x98\xB6"
```

**Comment by taschenb** [comment]
The `libnl` implementation does filter out any character in the SSID, that is not printable by the currently installed C locale. This probably interferes with something like emojis.   

By disabling this filter and passing through everything the kernel provides should fix this

**Comment by lyneca** [comment]
I'm still having the same problem after updating; when connected to a network with an emoji SSID, the module label is set to `label-disconnected`, and the IP address doesn't show.

**Comment by taschenb** [comment]
Are you using netlink (libnl-genl) or WEXT (wireless-tools) as wifi backend for polybar?

Currently you can build it with both. While the build process prefers libnl, it will automatically fall back to the deprecated WEXT in case the dependencies (libnl-genl) for libnl are missing.

As for the issue: I cannot reproduce this with libnl. A single emoji as SSID is sufficient for the connection to be recognized as connected.

You could test both backends by explicitly enforcing them with adding `-DWITH_LIBNL=ON` or `-DWITH_LIBNL=OFF` to your cmake command after you have cleaned your build directory.
In case the dependencies are not installed for the specified backend, the network module won't be included in the build. So make sure to install them first.

**Comment by lyneca** [comment]
Compiling with `-DWITH_LIBNL=ON` works for me!
