### ISSUE TITLE
Dropping Unmatched Character

### ISSUE THREAD

**Issue by krionical** [jaagr/polybar#392]
When I run polybar example (with the default config), I get this:

polybar example
warn: No monitor specified, using "DVI-I-2"
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: module/xbacklight: Could not get data (err: XCB_NAME (15))
error: Disabling module "xbacklight" (reason: Not supported for "DVI-I-2")
error: Disabling module "battery" (reason: No suitable way to get current charge state)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e0cb)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e0cb)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e0cb)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e0cb)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e0cb)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e0cb)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)

The unmatched character issue will run in a loop. As far as I know, I have all the requirements met to install Polybar. It seems like the modules re-load and I can't tell if it due to a font, or a module problem, or something else.

**Comment by pazz** [comment]
I get the same thing, I believe it is due to some utf-8 charcters in our config (the example config contains many of those).

My config contains

```
font-3 = FontAwesome:pixelsize=14;0
```

which should be present:
```
fc-match FontAwesome:pixelsize=14
FontAwesome.otf: "FontAwesome" "Regular"
```

Any ideas?

**Comment by jaagr** [comment]
The example config requires the `siji` font. Just remove/replace the unicode characters if you don't have the font.

**Comment by pazz** [comment]
OK, thanks. I am fighting to get this font installed here (debian testing). Dis anyone get this to work?
I suppose this issue is "solved" then and could be closed.

**Comment by krionical** [comment]
I have the siji font installed, or so that's what it says. I'd be happy to perform some checks on that if necessary.

**Comment by stooj** [comment]
OK, after quite a while fighting with this, I've managed to get rid of the warnings.

On my (Arch) box, siji is installed, but `font-2 = siji:pixelsize=10;1` does not match the actual font. Using `fc-match` I've managed to get it working by using the following two fonts:

```
font-0 = fixed:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = "Wuncon Siji:pixelsize=10;1"
```

**Comment by helionmelion** [comment]
yes changing to wuncon siji the bar was able to show the character from "format-prefix = " ! but the message still remains

**Comment by Deluxo** [comment]
My bitmap font's declaration stopped working, which looked like this: font-0 = -*-terminus-medium-r-*-*-12-*-*-*-*-*-iso10646-*;0
Using pango notation works, but now i get shitty pango rendering.
This is definitely a bug!

**Comment by jaagr** [comment]
@Deluxo X fonts are no longer supported. Try `font-0 = terminus:pixelsize=12`

**Comment by jhnguyy** [comment]
I'm having an interesting case of this as well.

`Dropping unmatched character  (U+0002)`

The thing is I am using plenty of fonts that should work with it.

`font-0 = roboto:pixelsize=13
font-1 = fontawesome:pixelsize=13
font-2 = dejavusans:pixelsize=13
font-3 = unifont:pixelsize=13`
(Sorry, I couldn't get the line breaks to work)

It broke while using Google Chrome, going to this [link](https://www.nytimes.com/2017/02/06/us/politics/donald-trump-administration.html?_r=0)

[This](http://www.fileformat.info/info/unicode/char/0002/fontsupport.htm) site says that the fonts I used above should work (Roboto/unifont).

Here are the fc-match outputs for the above fonts.
fc-match roboto:pixelsize=13 `Roboto-Regular.ttf: "Roboto"  "Regular"`
fc-match fontawesome:pixelsize=13 `fontawesome-webfont.ttf:  "FontAwesome"  "Regular"`
fc-match dejavusans:pixelsize=13 `DejaVuSans.ttf:  "DejaVu Sans"  "Book"`
fc-match unifont:pixelsize=13 `Unifont.ttf: "Unifont"  "Medium"`

polybar -v `polybar 3.0.4`

**Comment by jaagr** [comment]
this should be fixed @skystrife's pr (https://github.com/jaagr/polybar/pull/434)

**Comment by krionical** [comment]
My solution to this problem eventually involved migrating to arch linux. I wound up crawling through the guts of Ubuntu changes to the font system such as where fonts are stored and eventually discovered fontconfig was not playing nice for whatever reason with the unicode fonts. So, I made the fatal mistake of uninstall fontconfig which I figured was probably a bad idea, and it took about a zillion packages with it including something that lightdm needed which basically made a mess of everything. 

When I moved to arch and installed polybar, it worked fine. I think it has something to do with all the changes Ubuntu made to how fonts are stored and how that works with fontconfig. I hope your fix involves that somehow or accounts for it.

**Comment by jaagr** [comment]
Closing due to inactivity.

**Comment by JeremyKennedy** [comment]
I had the same issue, and fixed it with these commands:
```
# "Un-disable" bitmap fonts
sudo rm /etc/fonts/conf.d/70-no-bitmaps.conf
# Clear the font cache
sudo fc-cache -f -v
```

from: http://www.alanbriolat.co.uk/enable-bitmap-fonts-on-ubuntu-jaunty.html

**Comment by dessalines** [comment]
I'm still getting this issue, and none of the above fonts worked.

**Comment by isgk** [comment]
I'm too having the same issue. 
Using i3wm, Ubuntu 16.04LTS.

**Comment by mikroskeem** [comment]
Font Awesome stopped working after certain update. I have `ttf-font-awesome` installed from arch repo and set font-x to `"Font Awesome 5 Free:size=10:style=Regular"`, but fonts won't show up.

**Comment by felipecustodio** [comment]
For those like me that ended up here by searching for the 'Dropping Unmatched Character',[ the above answer should work](https://github.com/jaagr/polybar/issues/392#issuecomment-354564442), FA indeed updated and we should update our config files. 

https://fontawesome.com/cheatsheet

**Comment by sepastian** [comment]
If someone still needs this, here's how I got Siji to work under _Debian GNU/Linux buster/sid_.

Enable bitmap fonts with `dpkg-reconfigure fontconfig-config` (see https://wiki.debian.org/Fonts#Adding_fonts), probably better than manually removing `/etc/fonts/conf.d/70-no-bitmaps.conf`.

Install the Siji font as described at https://github.com/stark/siji, under `~/.fonts`. Load it by adding this to `~/.Xsession`.

```
xset +fp /home/sebastian/.fonts
xset fp rehash
```

Restart X and verify the font is available.

```
$ fc-list  | grep siji
/home/username/.fonts/siji.pcf: Siji:style=Regular
$ fc-match Siji
siji.pcf: "Siji" "Regular"
```

Setup fonts in polybar config.

```
font-0 = terminus:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = Siji:pixelsize=10;1
```

Works for me.

**Comment by Mardii-D-King** [comment]
I am running arch and for the longest time i kept having this issue. I am please to say though that after all my readings i found a solution that solve the error and may help others as well.

I thought i had the correct siji installed but then when i used `fc-match siji` my output was "Fura Mono Regular Nerd Font Complete Mono.otf: "FuraMono Nerd Font Mono" "Regular". Then i ran `fc-list |grep siji` and get no output.

The solution i found was to install the siji-git r22.9888311-1 version and it worked after installed and i restart i3. To install it i used `yay siji`.

Hope this was helpful.

**Comment by FrenzyExists** [comment]
Ok, so I have a prob with my fonts as well and my case is a bit different. On my KDE Neon I have a xfce-i3 setup and wanted to get polybar working as a replacement of the i3blocks. Problem is, I get this:
![image](https://user-images.githubusercontent.com/47986470/83311619-bda87680-a1dd-11ea-9d7f-79d62975a1e6.png)

The fonts I have are not bitmap fonts since my system has those blocked and can't install them. So I have these:

`
font-0 = "Fantasque Sans Mono:pixelsize=10;3"
font-1 = "Iosevka Nerd Font:pixelsize=13;3"
`
I can get it rendered n' all, but the charging animation doesn't stop cycling. I don't know if its a normal thing or not, but I keep getting this message on my terminal when launching polybar. I tried changing the number of icons, the icons themselves, anything I could think of. The discharging animation, however, is just fine, for now.

Here's my battery module setup:

`

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
full-at = 99

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ACAD

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 2

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <animation-charging> <label-charging>

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <ramp-capacity> <label-discharging>

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
;format-full = <ramp-capacity> <label-full>

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current charge rate in watts)

label-charging = %percentage%%

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = %percentage%%

; Available tokens:
;   %percentage% (default)
label-full = Fully Charged

; Only applies if <ramp-capacity> is used
format-full-prefix = " "
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 =  
ramp-capacity-8 = 
ramp-capacity-9 = 


ramp-capacity-0-foreground = ${color.red}
ramp-capacity-1-foreground = ${color.red}
ramp-capacity-foreground   = ${color.fg}
;bar-capacity-width = 10


; Only applies if <bar-capacity> is used
;bar-capacity-width = 10

; Only applies if <animation-charging> is used


animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 =   
animation-charging-3 = 
animation-charging-4 = 
animation-charging-5 = 
animation-charging-6 = 



; Framerate in milliseconds
animation-charging-framerate = 750
`

Does anyone know why I keep getting this error with the charging icons?

**Comment by coderjojo** [comment]
> I had the same issue, and fixed it with these commands:
> 
> ```
> # "Un-disable" bitmap fonts
> sudo rm /etc/fonts/conf.d/70-no-bitmaps.conf
> # Clear the font cache
> sudo fc-cache -f -v
> ```
> 
> from: http://www.alanbriolat.co.uk/enable-bitmap-fonts-on-ubuntu-jaunty.html

It worked for me but now my fonts are not rendering properly on Firefox and polybar. Any quick fix for it?
![Screenshot_2020-09-04 Dropping Unmatched Character · Issue #392 · polybar polybar](https://user-images.githubusercontent.com/45591748/92237700-736a1c00-eed5-11ea-8384-e16c182088b0.png)

**Comment by dzintars** [comment]
So, my Polybar set-up is locked into simple Ansible rule and recently it just started to fail:
![Siji](https://user-images.githubusercontent.com/547420/97789751-92cab000-1bcb-11eb-8d9d-11ec36d8ae89.png)
Definitely Siji is there and i have no any other font issues at all.
Any more ideas, how to troubleshoot this?

**Comment by patrick96** [comment]
@dzintars Those dropped characters don't look like siji characters, pretty sure they are from FontAwesome and you don't have FontAwesome in your font list.
Are you sure the launch script uses the config at `~/.config/polybar/config` or does it set some other path?

Also, polybar nevers load the config from `/usr/local/share/doc/polybar/config` unless you explicitly specify it.

**Comment by dzintars** [comment]
@patrick96 How about... i am a tired idiot? Editing just a Ansible rule files does not mean they will take an effect automatically... 😅 I just was in wrong context and was thinking that i am editing actual config file. Should i delete my issue above?

**Comment by patrick96** [comment]
I think we all had these moments :smile: 

You can leave it. Doesn't really matter.

**Comment by velespr0** [comment]
Debian linux 11 
Install Siji font as described at [](https://github.com/stark/siji)
Create an exception rule for siji [https://owl.eu.com/posts/debian-demystified-installing-bitmap-fonts.html](url)

**Comment by Twix53791** [comment]
A noob answer : first check if you are not trying to use a non existent character. I just loose 1h of my life trying to understand why I couldn't display  a weather icon from nerd font on my polybar. I was in fact trying using the unicode character got from the nerd font site ([https://www.nerdfonts.com/cheat-sheet?set=nf-weather-](url)), but it is not the same on my computer, as I simply saw it on Libbre Office Writer... It was in fact so simple... Like always in the noob life...

**Comment by xcenai** [comment]
> A noob answer : first check if you are not trying to use a non existent character. I just loose 1h of my life trying to understand why I couldn't display a weather icon from nerd font on my polybar. I was in fact trying using the unicode character got from the nerd font site ([https://www.nerdfonts.com/cheat-sheet?set=nf-weather-](url)), but it is not the same on my computer, as I simply saw it on Libbre Office Writer... It was in fact so simple... Like always in the noob life...

Can you make this more understandable. It doesn't make any sense.

**Comment by Goosegit11** [comment]
I am using the mpd module with the configuration example from the polybar wiki. This is the error I have:
```
warn: Dropping unmatched character '𝄞' (U+1d11e) in ' 𝄞 Escape From Midwich Valley'
warn: Dropping unmatched character '🔁' (U+1f501) in '🔁'
warn: Dropping unmatched character '🔀' (U+1f500) in '🔀'
warn: Dropping unmatched character '𝄞' (U+1d11e) in ' 𝄞 Escape From Midwich Valley'
warn: Dropping unmatched character '🔁' (U+1f501) in '🔁'
warn: Dropping unmatched character '🔀' (U+1f500) in '🔀'
warn: Dropping unmatched character '𝄞' (U+1d11e) in ' 𝄞 Escape From Midwich Valley'
```


I have this in my polybar config:
```
font-0 = "Iosevka Nerd Font Propo,Iosevka NFP Medium:style=Medium,Regular:pixelsize=14;2
font-1 = "Symbols Nerd Font:style=Regular"
font-2 = "FontAwesome:style=Regular"
font-3 = "Siji:style=Regular:pixelsize=10;1"
```

Output of `fc-list | grep siji`: (I tried copying to the `.local/share/fonts`)
```
/usr/share/fonts/misc/siji.bdf: Siji:style=Regular
/home/huuh/.local/share/fonts/siji.bdf: Siji:style=Regular
```

There was no `no-bitmaps` conf. 
I even manually added the `yes-bitmaps` conf, still no luck.

**Comment by Xlaits** [comment]
Arch user here: Still having this issue myself, similar to the comment directly above. Siji installed from AUR using yay. I've tried all three versions that have showed up to no avail.
