### ISSUE TITLE
Polybar Dependency 

### ISSUE THREAD

**Issue by AvnSgt** [jaagr/polybar#871]
Polybar requires jsoncpp to run. Recently **jsoncpp** seems to have changed their versioning, which has cause Polybar to fail to load and showing the following error when run manually: **polybar: error while loading shared libraries: libjsoncpp.so.11: cannot open shared object file.** The current version of jsoncpp is 1.8.3, which was pushed out to the Arch Repositories, and upon update, libjsoncpp.so.11 is replaced with libjsoncpp.so.1.8.3

**Comment by CuriouslyCurious** [comment]
Can confirm that I am having the same issue.

**Comment by medioman** [comment]
+1

**Comment by patrick96** [comment]
You'll need to recompile polybar so that the proper library file is linked. It is possible that the build will fail with the new jsoncpp version (see #741). If this happens you will also have to apply [this](https://github.com/jaagr/i3ipcpp/pull/4) patch to the `i3ipcpp` submodule.

**Comment by AvnSgt** [comment]
@patrick96 - This is a in-term fix correct? With a full fix coming later, through the AUR, if I understood the issue thread _#741_, and the overall intent.

**Comment by patrick96** [comment]
Yes. The contents of the fix are likely to stay the same, but I have to test it a little first, before I can fully integrate it into the project.

**Comment by hiteshpaul** [comment]
+1

**Comment by dddent** [comment]
Could someone give me a few directions on how to apply the patch? Can I add it to the PKGBUILD somehow?

**Comment by patrick96** [comment]
In the AUR comments (https://aur.archlinux.org/packages/polybar) someone has posted a PKGBUILD with the patch applied. **Note:** I did not vet that PKGBUILD, so use with care.

**Comment by dddent** [comment]
Thanks! Will try that.

**Comment by Jolt2bolt** [comment]
I fixed the problem creating a copy of libjsoncpp.so.1.8.3 and renaming it to libjsoncpp.so.11 although that a temporary solution!:P

**Comment by patrick96** [comment]
@Jolt2bolt do you have an active i3 module in your bar and it still works?

**Comment by Jolt2bolt** [comment]
I have the Wireless module and works fina after cloning ibjsoncpp.so.1.8.3 and renaming as libjsoncpp.so.11

**Comment by CuriouslyCurious** [comment]
After doing the fix @Jolt2bolt mentioned Polybar is working flawlessly again.

**Comment by patrick96** [comment]
Renaming will probably only work if the i3 module is not used.

**Comment by CuriouslyCurious** [comment]
@patrick96 This does not seem to be the case, for me at least.

![image](https://user-images.githubusercontent.com/10660675/33490249-ce824fde-d6b6-11e7-85fa-a2b2d75350a6.png)

**Comment by icp1994** [comment]
is downgrading jsoncpp a good idea?

**Comment by tjade273** [comment]
For a quick fix it worked for me to just symlink 

     sudo ln -s /lib/libjsoncpp.so.1.8.3 /lib/libjsoncpp.so.11

**Comment by rault-a** [comment]
I fixed the issue by reinstalling polybar, without creating link

**Comment by edbizarro** [comment]
tjade273's fix works for me

**Comment by obsoke** [comment]
I tried both symlinking and moving libjsoncpp `/lib/libjsoncpp.so.11` but I stlil get deprecation errors when trying to compile. Using the i3 module.

**Comment by AHaymond** [comment]
recompiling polybar has fixed this issue for me.

**Comment by patrick96** [comment]
@obsoke you have to apply a patch to the i3ipcpp submodule, as described in my answer [here](https://github.com/jaagr/polybar/issues/871#issuecomment-348355198)

**Comment by AvnSgt** [comment]
@patrick96 Will close this when you give me the go ahead. I don't think we need to beat a dead horse, as there are several ways to work around the issue, until the fix is applied. What do you think?

**Comment by patrick96** [comment]
I think we should keep this open until the fix is merged, just to have a central location with all the workarounds where we can point people to.
I will close this once I test and merge the fix

**Comment by patrick96** [comment]
I just merged the fix. The build errors in the `polybar-git` should now be fixed. The `polybar` package will keep failing to build until the 3.1.0 release, which is just around the corner.

**Comment by mezklador** [comment]
I've just switch today from `polybar-git` to `polybar`. Everything works fine then...

**Comment by bavarianbidi** [comment]
the switch from `polybar-git` to `polybar` works for me too

**Comment by Jezorko** [comment]
As this issue still persist (I just installed polybar via `yay` and got the same error), maybe it would be wise to remove AUR packages that aren't working? @patrick96

**Comment by codedumps** [comment]
It helped me:

```bash
$ yay -S jsoncpp 
```
