### ISSUE TITLE
 Cannot open shared object file libjsoncpp.so

### ISSUE THREAD

**Issue by notaduck** [jaagr/polybar#885]
I'm getting this error code while trying to start polybar
```
[daniel@laptop ~]$ polybar main
polybar: error while loading shared libraries: libjsoncpp.so.11: cannot open shared object file: No such file or directory
```

However jsoncpp should be installed.
```
[daniel@laptop ~]$ yaourt jsoncpp
1 extra/jsoncpp 1.8.3-1 [installed]
    C++ library for interacting with JSO
```

**Comment by patrick96** [comment]
You have to recompile polybar, see #871

**Comment by notaduck** [comment]
Thanks! It seems like the AUR package has been fixed too.

**Comment by dessalines** [comment]
This problem just popped up again.

**Comment by patrick96** [comment]
The fix for it didn't change. You have to recompile polybar.

**Comment by yn5** [comment]
Uninstalling and reinstalling works as well.

**Comment by belminf** [comment]
@yn5 reinstalling the AUR package? I tried that:

```bash
$ sudo pacman -R polybar
$ cd ~/aur/polybar
$ makepkg -si
```

Still getting the same error. Unsure how that was suppose to update the linking to the library though. Please elaborate.

**Comment by patrick96** [comment]
Reinstalling only works, if it actually recompiles polybar. You'll have to pass the `-f` flag to `makepkg` or remove the already built binaries from your `~/aur/polybar/` folder

**Comment by Jezorko** [comment]
@yn5 note that _reinstalling_ using AUR is exactly that: the whole app is recompiled

**Comment by yn5** [comment]
@Jezorko, I don't believe I ever said it isn't, but thanks for the note :blush:

**Comment by armin86er** [comment]
Rebuilding doesn't work in my case on Arch. I did three times `pikaur -S --rebuild polybar`. 
Resulting Error when starting `polybar` is every time the missing `libjsoncpp` shared object.

Not sure if this build informations are relevant (if not, say so, I'll edit and delete)
```
Targets:
[X]   polybar-msg
[ ]   testsuite
 Module support:
[X]   alsa (1.1.7)
[X]   curl (7.62.0)
[X]   i3
[ ]   mpd
[X]   network (3.4.0)
[X]   pulseaudio (12.2)
[X]   xkeyboard (1.13.1)
 X extensions:
[X]   xcb-randr (1.13.1)
[X]   xcb-randr (monitor support) (1.13.1)
[ ]   xcb-render
[ ]   xcb-damage
[ ]   xcb-sync
[ ]   xcb-composite
[X]   xcb-xkb (1.13.1)
[X]   xcb-xrm (1.3)
[X]   xcb-cursor (0.1.3)
```
Build process also puts missing fonts in output. But seems like an info rather than an error.

**Comment by avanasear** [comment]
Same thing again - libjsoncpp was updated. Recompiling fixes the issue.

**Comment by PonasKovas** [comment]
I'm sorry, this is probably not the best place to ask this, but how exactly updating a library can break a package, and why recompiling fixes it?

**Comment by jazoom** [comment]
@PonasKovas I think this is why:

https://github.com/polybar/polybar/wiki/Known-Issues#error-while-loading-shared-libraries-libjsoncpp

**Comment by Jezorko** [comment]
Isn't this a bug in libjsoncpp that the install / update script doesn't create a link to the newest version of the library?

**Comment by jazoom** [comment]
I checked the symlink after updating and seeing this error. There was already a link to the new library version, exactly as recommended in that "known issues" section. I don't know why it didn't work. But re-compiling fixed it.

**Comment by patrick96** [comment]
When jsoncpp introduces possibly breaking changes to its library, it will bump the so called `SONAME` field in the library. If you compiled polybar with `jsoncpp 1.8.4`, polybar was linked against `libjsoncpp.so.20`. So everytime the `polybar` exectuable is run, the operating system will search for the `libjsoncpp.so.20` file for dynamic linking. Now if you update jsoncpp to version 1.9.1, which comes with `libjsoncpp.so.21`, the OS can no longer find `libjsoncpp.so.20` when running polybar and will crash with the mentioned error message.

This is neither a bug in polybar nor in jsoncpp @Jezorko. This is one of the downsides of polybar not being pre-packaged on many platforms because you can update jsoncpp without needing to re-link polybar.

**Comment by ginglis13** [comment]
I was able to solve this on Arch `5.2.14-arch2-1-ARCH` using yay. I simply ran `yay -S polybar`, waiting for the reinstallation/compilation to finish, and polybar was back to working as expected (for me at least).

**Comment by PonasKovas** [comment]
> I was able to solve this on Arch `5.2.14-arch2-1-ARCH` using yay. I simply ran `yay -S polybar`, waiting for the reinstallation/compilation to finish, and polybar was back to working as expected (for me at least).

@ginglis13 Yeah, because, just as it was mentioned multiple times before, *recompiling* fixes the issue.

**Comment by Cory-Watson** [comment]
Just ran into this myself..

Why is it that polybar links to `libjsoncpp.so.XX` instead of `libjsoncpp.so`?

**Comment by patrick96** [comment]
@Cory-Watson 
> Why is it that polybar links to libjsoncpp.so.XX instead of libjsoncpp.so?

This is guided by linker internals. If you link to a shared library, the linker will actually link to the `SONAME` which is `libjsoncpp.so.XX`, nothing we can do about that I think. 

Also linking directly to `libjsoncpp.so` isn't a good idea because the whole point of `SONAME` is to prevent running an executable with a library that is incompatible (has a different `SONAME`). For that reason creating the symlink is also not a good idea. In the case of jsoncpp it's probably fine, but imagine `libjsoncpp.so.21` is completely different from `libjsoncpp.so.20`, now you run polybar which is linked to `libjsoncpp.so.20` with the symlink that points to `libjsoncpp.so.21`. In the best case, polybar won't even start because of a linker error, in the worst case the calls that polybar makes to jsoncpp have malformed inputs and produce unexpected outputs or undefined behavior.

**Comment by thomai** [comment]
I just had the same problem. Reinstalling polybar worked for me. Thanks.

**Comment by StitiFatah** [comment]
Already got the same problem few months ago and completely reinstalling from the AUR worked well but this time it doesn't fix the problem, I've tried with polybar and polybar-git 
`polybar: error while loading shared libraries: libjsoncpp.so.22: cannot open shared object file: No such file or directory
`

**Comment by dee-see** [comment]
Same problem here, recompiled and installed the `jsoncpp` package (on Arch) and still not working.

**Comment by dee-see** [comment]
Installing `jsoncpp` and then reinstalling `polybar-git` worked for me (on Arch)

**Comment by botiapa** [comment]
Same, reinstalling `jsoncpp` and switching to `polybar-git` worked for me as well

**Comment by StitiFatah** [comment]
> Same, reinstalling `jsoncpp` and switching to `polybar-git` worked for me as well

Still doesn't solve the issue for me

**Comment by manuelmaceira** [comment]
Had this issue again today but now reinstalling polybar from AUR didn't work, neither switching to polybar-git nor reinstalling jsoncpp

**Comment by patrick96** [comment]
I have locked this issue because it was generating too much noise.

The fix is (and has been the same for years) to **recompile** polybar. Just reinstalling is often not enough because it generally doesn't recompile polybar.

This is also described on the [Known Issues page](https://github.com/polybar/polybar/wiki/Known-Issues#error-while-loading-shared-libraries-libjsoncpp).
